/**
 * Create Patient Task API
 *
 * POST /api/prevention/hub/create-patient-task
 * Assigns patient self-care tasks from prevention recommendations.
 * Tasks are tracked via ProviderTask and can trigger notifications.
 *
 * Request Body:
 * - patientId: string (required) - Patient ID
 * - title: string (required) - Task title
 * - description: string (required) - Task description/instructions
 * - taskType: string (optional, default: 'self_care')
 * - dueDate: Date (optional) - When task should be completed by
 * - linkedInterventionId: string (optional) - Link to prevention intervention
 *
 * Phase 5: Hub Actions & Clinical Workflows
 */

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession, authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import logger from '@/lib/logger';
import { z } from 'zod';
import { auditCreate } from '@/lib/audit';

export const dynamic = 'force-dynamic';

// Request validation schema
const CreatePatientTaskSchema = z.object({
  patientId: z.string().min(1, 'patientId is required'),
  title: z.string().min(1, 'title is required'),
  description: z.string().min(1, 'description is required'),
  taskType: z.string().default('self_care'),
  dueDate: z.string().datetime().optional(),
  linkedInterventionId: z.string().optional(),
});

// Map task type to task category
const taskTypeToCategory = {
  self_care: 'GENERAL' as const,
  appointment: 'APPOINTMENT' as const,
  medication: 'PRESCRIPTION' as const,
  follow_up: 'FOLLOW_UP' as const,
  documentation: 'DOCUMENTATION' as const,
};

/**
 * POST /api/prevention/hub/create-patient-task
 * Create a patient self-care task
 */
export async function POST(request: NextRequest) {
  const start = performance.now();

  try {
    // Verify authentication
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json(
        { error: 'Unauthorized - Please log in' },
        { status: 401 }
      );
    }

    // Parse and validate request body
    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: 'Invalid JSON in request body' },
        { status: 400 }
      );
    }

    const validation = CreatePatientTaskSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        {
          error: 'Validation failed',
          details: validation.error.errors,
        },
        { status: 400 }
      );
    }

    const { patientId, title, description, taskType, dueDate, linkedInterventionId } = validation.data;

    // Verify patient exists
    const patient = await prisma.patient.findUnique({
      where: { id: patientId },
      select: { id: true, firstName: true, lastName: true, email: true },
    });

    if (!patient) {
      return NextResponse.json(
        { error: 'Patient not found' },
        { status: 404 }
      );
    }

    // Get the task category
    const category = taskTypeToCategory[taskType as keyof typeof taskTypeToCategory] || 'GENERAL';

    // Create the patient task as a ProviderTask
    const patientTask = await prisma.providerTask.create({
      data: {
        title,
        description,
        category,
        priority: 'NORMAL',
        status: 'PENDING',
        assignedTo: session.user.id,
        relatedType: 'Patient',
        relatedId: patientId,
        autoGenerated: true,
        generatedBy: 'prevention_hub_patient_task',
        dueDate: dueDate ? new Date(dueDate) : undefined,
      },
    });

    // If linked to a screening intervention, update the screening
    if (linkedInterventionId) {
      try {
        await prisma.screeningOutcome.update({
          where: { id: linkedInterventionId },
          data: {
            notes: `Patient task assigned: ${title}`,
          },
        });
      } catch (linkError) {
        // Log but don't fail - the task is already created
        logger.warn({
          event: 'patient_task_intervention_link_failed',
          interventionId: linkedInterventionId,
          taskId: patientTask.id,
          error: linkError instanceof Error ? linkError.message : String(linkError),
        });
      }
    }

    const elapsed = performance.now() - start;

    logger.info({
      event: 'patient_task_created',
      taskId: patientTask.id,
      taskType,
      patientId,
      userId: session.user.id,
      hasDueDate: !!dueDate,
      latencyMs: elapsed.toFixed(2),
    });

    // HIPAA Audit
    await auditCreate('PatientTask', patientTask.id, request, {
      action: 'patient_task_created',
      taskType,
      title,
      patientId,
      createdBy: session.user.id,
      dueDate,
      linkedInterventionId,
    });

    return NextResponse.json({
      success: true,
      data: {
        task: {
          id: patientTask.id,
          patientId,
          title,
          description,
          taskType,
          status: 'PENDING',
          dueDate: patientTask.dueDate,
          linkedInterventionId,
          createdAt: patientTask.createdAt,
        },
      },
      meta: {
        latencyMs: Math.round(elapsed),
      },
    });
  } catch (error) {
    const elapsed = performance.now() - start;

    logger.error({
      event: 'create_patient_task_error',
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
      latencyMs: elapsed.toFixed(2),
    });

    return NextResponse.json(
      {
        error: 'Failed to create patient task',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
