/**
 * Seed the HerbalContraindication table from the SPAQI 2020 Consensus
 * Statement on Preoperative Dietary Supplements (Mayo Clin Proc.
 * 2020;95(6):1344-1360, S0025-6196(20)30920-4), plus widely accepted
 * supplementary entries from NCCIH and Cleveland Clinic guidance.
 *
 * Idempotent — upsert on slug. Run after `prisma db push`.
 *
 * Hold-day values reflect the SPAQI consensus recommendation; where SPAQI
 * gives a range (e.g. "1-2 weeks") we use the conservative high end.
 */
import { PrismaClient, HerbalEvidenceLevel, HerbalRiskCategory, MedicalSystemType } from '@prisma/client';

const prisma = new PrismaClient();

interface HerbalSeed {
  slug: string;
  commonName: string;
  scientificName: string;
  aliases?: string[];
  commonNamePt?: string;
  commonNameEs?: string;
  holdDaysPreOp: number;
  mechanism: string;
  clinicalConcern: string;
  primaryRiskCategory: HerbalRiskCategory;
  riskCategories?: HerbalRiskCategory[];
  evidenceLevel?: HerbalEvidenceLevel;
  citationPmid?: string;
  additionalPmids?: string[];
  interactingMedClasses?: string[];
  commonInSystemTypes?: MedicalSystemType[];
  traditionalUses?: string[];
  mustDiscloseToAnesthesia?: boolean;
}

const SPAQI_PMID = '32540015'; // SPAQI Consensus — Mayo Clin Proc 2020

const HERBALS: HerbalSeed[] = [
  // ── 14-day holds (highest risk — SPAQI tier 1) ────────────────────────────
  {
    slug: 'ginkgo-biloba',
    commonName: 'Ginkgo biloba',
    scientificName: 'Ginkgo biloba L.',
    aliases: ['ginkgo', 'maidenhair tree'],
    commonNamePt: 'Ginkgo biloba',
    commonNameEs: 'Ginkgo biloba',
    holdDaysPreOp: 14,
    mechanism: 'Ginkgolides inhibit platelet-activating factor; case reports of spontaneous intracranial and postoperative bleeding.',
    clinicalConcern: 'Increased bleeding risk during and after surgery. Stop at least 14 days before any planned procedure.',
    primaryRiskCategory: 'BLEEDING',
    riskCategories: ['BLEEDING'],
    evidenceLevel: 'B',
    citationPmid: SPAQI_PMID,
    additionalPmids: ['11762566'],
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT', 'NSAID', 'SSRI'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY'],
    traditionalUses: ['Cognitive support', 'Peripheral circulation', 'Tinnitus'],
  },
  {
    slug: 'garlic',
    commonName: 'Garlic (concentrated extract)',
    scientificName: 'Allium sativum',
    aliases: ['allium'],
    commonNamePt: 'Alho',
    commonNameEs: 'Ajo',
    holdDaysPreOp: 14,
    mechanism: 'Allicin and related organosulfurs irreversibly inhibit platelet aggregation.',
    clinicalConcern: 'Additive antiplatelet effect with NSAIDs, aspirin, or anticoagulants. Culinary amounts are fine; stop concentrated supplements 14 days pre-op.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'B',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT', 'NSAID'],
    commonInSystemTypes: ['COMPLEMENTARY', 'TRADITIONAL'],
    traditionalUses: ['Cardiovascular support', 'Immune support'],
  },
  {
    slug: 'ginseng-asian',
    commonName: 'Asian ginseng',
    scientificName: 'Panax ginseng',
    aliases: ['Korean ginseng', 'red ginseng'],
    commonNamePt: 'Ginseng',
    commonNameEs: 'Ginseng',
    holdDaysPreOp: 14,
    mechanism: 'Ginsenosides inhibit platelet aggregation irreversibly and can lower blood glucose.',
    clinicalConcern: 'Risk of bleeding and intraoperative hypoglycemia, particularly in diabetic patients.',
    primaryRiskCategory: 'BLEEDING',
    riskCategories: ['BLEEDING', 'GLYCEMIC'],
    evidenceLevel: 'B',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT', 'HYPOGLYCEMIC', 'INSULIN', 'WARFARIN'],
    commonInSystemTypes: ['TRADITIONAL'],
    traditionalUses: ['Fatigue', 'Immune support', 'Glycemic modulation'],
  },
  {
    slug: 'ephedra',
    commonName: 'Ephedra',
    scientificName: 'Ephedra sinica',
    aliases: ['ma huang'],
    commonNamePt: 'Efedra',
    commonNameEs: 'Efedra',
    holdDaysPreOp: 14,
    mechanism: 'Sympathomimetic alkaloids (ephedrine, pseudoephedrine) cause tachycardia, hypertension, and refractory hypotension under anesthesia from catecholamine depletion.',
    clinicalConcern: 'Life-threatening hemodynamic instability under general anesthesia. Risk of arrhythmia, MI, and stroke. Avoid entirely pre-op; banned as a supplement in the US (2004) and many LATAM jurisdictions.',
    primaryRiskCategory: 'CARDIOVASCULAR',
    riskCategories: ['CARDIOVASCULAR'],
    evidenceLevel: 'A',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['MAO_INHIBITOR', 'SYMPATHOMIMETIC', 'BETA_BLOCKER'],
    commonInSystemTypes: ['TRADITIONAL'],
    traditionalUses: ['TCM bronchodilator (historical)', 'Weight loss products (banned)'],
  },
  {
    slug: 'kava-kava',
    commonName: 'Kava kava',
    scientificName: 'Piper methysticum',
    aliases: ['kava'],
    commonNamePt: 'Kava',
    commonNameEs: 'Kava',
    holdDaysPreOp: 14,
    mechanism: 'Kavalactones potentiate GABA-A — additive CNS depression with anesthetics and benzodiazepines. Associated with severe hepatotoxicity and fulminant hepatic failure.',
    clinicalConcern: 'Prolonged sedation, enhanced anesthetic effect, and risk of hepatic injury. Stop 14 days pre-op.',
    primaryRiskCategory: 'HEPATOTOXICITY',
    riskCategories: ['HEPATOTOXICITY', 'CNS_SEDATION'],
    evidenceLevel: 'B',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['BENZODIAZEPINE', 'OPIOID', 'ALCOHOL', 'HEPATOTOXIC'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY'],
    traditionalUses: ['Anxiety', 'Sleep', 'Pacific Islander ceremonial'],
  },
  {
    slug: 'st-johns-wort',
    commonName: "St. John's wort",
    scientificName: 'Hypericum perforatum',
    commonNamePt: 'Erva-de-São-João',
    commonNameEs: 'Hierba de San Juan',
    holdDaysPreOp: 14,
    mechanism: 'Potent inducer of CYP3A4, CYP2C9, and P-glycoprotein — accelerates metabolism of cyclosporine, warfarin, oral contraceptives, protease inhibitors, and many anesthetics. Serotonergic activity risks serotonin syndrome.',
    clinicalConcern: 'Loss of therapeutic effect of many drugs including immunosuppressants; risk of graft rejection. Risk of serotonin syndrome with anesthetic serotonergics (meperidine, tramadol, fentanyl).',
    primaryRiskCategory: 'CYP_INTERACTION',
    riskCategories: ['CYP_INTERACTION', 'SEROTONIN_SYNDROME'],
    evidenceLevel: 'A',
    citationPmid: SPAQI_PMID,
    additionalPmids: ['15009786'],
    interactingMedClasses: ['SSRI', 'MAO_INHIBITOR', 'WARFARIN', 'CYP3A4_SUBSTRATE', 'IMMUNOSUPPRESSANT', 'ORAL_CONTRACEPTIVE', 'PROTEASE_INHIBITOR'],
    commonInSystemTypes: ['COMPLEMENTARY', 'TRADITIONAL'],
    traditionalUses: ['Mild-to-moderate depression'],
  },
  {
    slug: 'valerian',
    commonName: 'Valerian',
    scientificName: 'Valeriana officinalis',
    commonNamePt: 'Valeriana',
    commonNameEs: 'Valeriana',
    holdDaysPreOp: 14,
    mechanism: 'GABA-A positive modulator — additive sedation with anesthetics. Chronic use may produce benzodiazepine-like withdrawal; taper gradually rather than abrupt stop.',
    clinicalConcern: 'Prolonged sedation, delayed emergence from anesthesia. If used chronically, taper over 1-2 weeks to avoid withdrawal (insomnia, anxiety, seizures).',
    primaryRiskCategory: 'CNS_SEDATION',
    riskCategories: ['CNS_SEDATION', 'WITHDRAWAL'],
    evidenceLevel: 'B',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['BENZODIAZEPINE', 'OPIOID', 'ALCOHOL', 'BARBITURATE'],
    commonInSystemTypes: ['COMPLEMENTARY', 'TRADITIONAL'],
    traditionalUses: ['Insomnia', 'Anxiety'],
  },
  {
    slug: 'echinacea',
    commonName: 'Echinacea',
    scientificName: 'Echinacea purpurea',
    commonNamePt: 'Equinácea',
    commonNameEs: 'Equinácea',
    holdDaysPreOp: 14,
    mechanism: 'Immunomodulatory effects and possible hepatotoxicity with prolonged use. CYP1A2 and CYP3A4 inhibition.',
    clinicalConcern: 'Theoretical risk of graft rejection in transplant patients and allograft complications. Possible interaction with immunosuppressants and hepatotoxic drugs.',
    primaryRiskCategory: 'HEPATOTOXICITY',
    riskCategories: ['HEPATOTOXICITY', 'CYP_INTERACTION'],
    evidenceLevel: 'C',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['IMMUNOSUPPRESSANT', 'HEPATOTOXIC', 'CYP3A4_SUBSTRATE'],
    commonInSystemTypes: ['COMPLEMENTARY', 'TRADITIONAL'],
    traditionalUses: ['Upper respiratory infection prevention', 'Immune support'],
  },

  // ── 7-day holds (SPAQI tier 2) ───────────────────────────────────────────
  {
    slug: 'feverfew',
    commonName: 'Feverfew',
    scientificName: 'Tanacetum parthenium',
    commonNamePt: 'Matricária',
    commonNameEs: 'Matricaria',
    holdDaysPreOp: 7,
    mechanism: 'Parthenolide inhibits platelet aggregation and serotonin release.',
    clinicalConcern: 'Additive bleeding with anticoagulants, antiplatelets, and NSAIDs.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'C',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT', 'NSAID'],
    commonInSystemTypes: ['COMPLEMENTARY', 'TRADITIONAL'],
    traditionalUses: ['Migraine prevention'],
  },
  {
    slug: 'fish-oil-high-dose',
    commonName: 'Fish oil / Omega-3 (>3 g/day)',
    scientificName: 'Omega-3 fatty acids (EPA + DHA)',
    aliases: ['omega-3', 'EPA', 'DHA'],
    commonNamePt: 'Óleo de peixe',
    commonNameEs: 'Aceite de pescado',
    holdDaysPreOp: 7,
    mechanism: 'EPA/DHA inhibit thromboxane A2 synthesis — antiplatelet effect is dose-dependent. Low doses (<1 g/day) have minimal effect.',
    clinicalConcern: 'Bleeding risk at doses above 3 g/day. Cardiology-prescribed prescription omega-3 requires physician-directed hold decision; do not stop autonomously.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'B',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT'],
    commonInSystemTypes: ['CONVENTIONAL', 'INTEGRATIVE'],
    traditionalUses: ['Cardiovascular health', 'Anti-inflammatory'],
  },
  {
    slug: 'vitamin-e-high-dose',
    commonName: 'Vitamin E (>400 IU/day)',
    scientificName: 'Tocopherol',
    commonNamePt: 'Vitamina E',
    commonNameEs: 'Vitamina E',
    holdDaysPreOp: 7,
    mechanism: 'High-dose tocopherol impairs vitamin K-dependent clotting factor function and platelet aggregation.',
    clinicalConcern: 'Bleeding risk with anticoagulants. Multivitamin-level doses are safe; stop high-dose single supplements.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'B',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['ANTICOAGULANT', 'ANTIPLATELET', 'WARFARIN'],
    commonInSystemTypes: ['CONVENTIONAL', 'INTEGRATIVE', 'COMPLEMENTARY'],
  },
  {
    slug: 'ginger-high-dose',
    commonName: 'Ginger (concentrated extract)',
    scientificName: 'Zingiber officinale',
    commonNamePt: 'Gengibre',
    commonNameEs: 'Jengibre',
    holdDaysPreOp: 7,
    mechanism: 'Gingerols mildly inhibit thromboxane synthesis.',
    clinicalConcern: 'Mild antiplatelet effect at high supplement doses. Culinary and anti-nausea doses (1 g/day) are low-risk and may be continued for post-op nausea prophylaxis.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'C',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY', 'INTEGRATIVE'],
    traditionalUses: ['Nausea', 'Digestive support', 'TCM warming herb'],
  },
  {
    slug: 'saw-palmetto',
    commonName: 'Saw palmetto',
    scientificName: 'Serenoa repens',
    commonNamePt: 'Saw palmetto',
    commonNameEs: 'Palma enana americana',
    holdDaysPreOp: 7,
    mechanism: 'Inhibits COX and 5-alpha-reductase; mild antiplatelet activity.',
    clinicalConcern: 'Bleeding risk, especially urologic procedures where it is commonly used for BPH.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'C',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT', 'NSAID'],
    commonInSystemTypes: ['COMPLEMENTARY', 'INTEGRATIVE'],
    traditionalUses: ['Benign prostatic hyperplasia'],
  },
  {
    slug: 'black-cohosh',
    commonName: 'Black cohosh',
    scientificName: 'Actaea racemosa',
    aliases: ['Cimicifuga racemosa'],
    commonNamePt: 'Cohosh preto',
    commonNameEs: 'Cimicífuga',
    holdDaysPreOp: 7,
    mechanism: 'Case reports of hepatotoxicity including fulminant hepatic failure requiring transplantation.',
    clinicalConcern: 'Risk of hepatic injury. Disclose to anesthesia for LFT monitoring.',
    primaryRiskCategory: 'HEPATOTOXICITY',
    evidenceLevel: 'C',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['HEPATOTOXIC'],
    commonInSystemTypes: ['COMPLEMENTARY', 'TRADITIONAL'],
    traditionalUses: ['Menopausal symptoms', 'Hot flashes'],
  },
  {
    slug: 'dong-quai',
    commonName: 'Dong quai',
    scientificName: 'Angelica sinensis',
    commonNamePt: 'Dong quai',
    commonNameEs: 'Dong quai',
    holdDaysPreOp: 7,
    mechanism: 'Contains coumarin derivatives with anticoagulant activity; photosensitizing furanocoumarins.',
    clinicalConcern: 'Enhanced anticoagulation with warfarin and heparin. Photosensitivity reactions.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'C',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['ANTICOAGULANT', 'ANTIPLATELET', 'WARFARIN'],
    commonInSystemTypes: ['TRADITIONAL'],
    traditionalUses: ['TCM gynecologic tonic', 'Menstrual support'],
  },
  {
    slug: 'goldenseal',
    commonName: 'Goldenseal',
    scientificName: 'Hydrastis canadensis',
    commonNamePt: 'Hidraste',
    commonNameEs: 'Sello de oro',
    holdDaysPreOp: 7,
    mechanism: 'Berberine inhibits CYP3A4 and CYP2D6; may cause hypertension and vasoconstriction at high doses.',
    clinicalConcern: 'Drug interactions via CYP inhibition; hypertension risk.',
    primaryRiskCategory: 'CYP_INTERACTION',
    riskCategories: ['CYP_INTERACTION', 'CARDIOVASCULAR'],
    evidenceLevel: 'C',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['CYP3A4_SUBSTRATE', 'CYP2D6_SUBSTRATE', 'ANTIHYPERTENSIVE'],
    commonInSystemTypes: ['COMPLEMENTARY', 'TRADITIONAL'],
    traditionalUses: ['Upper respiratory infections', 'Native American medicine'],
  },
  {
    slug: 'grape-seed-extract',
    commonName: 'Grape seed extract',
    scientificName: 'Vitis vinifera seed extract',
    commonNamePt: 'Extrato de semente de uva',
    commonNameEs: 'Extracto de semilla de uva',
    holdDaysPreOp: 7,
    mechanism: 'Oligomeric proanthocyanidins inhibit platelet aggregation at supplement doses.',
    clinicalConcern: 'Additive antiplatelet effect.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'C',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT'],
    commonInSystemTypes: ['COMPLEMENTARY'],
  },
  {
    slug: 'turmeric-high-dose',
    commonName: 'Turmeric / curcumin (concentrated extract)',
    scientificName: 'Curcuma longa',
    aliases: ['curcumin'],
    commonNamePt: 'Açafrão-da-terra',
    commonNameEs: 'Cúrcuma',
    holdDaysPreOp: 7,
    mechanism: 'Curcumin inhibits platelet aggregation and CYP3A4 at high supplement doses.',
    clinicalConcern: 'Bleeding risk at concentrated supplement doses. Culinary amounts are low risk.',
    primaryRiskCategory: 'BLEEDING',
    riskCategories: ['BLEEDING', 'CYP_INTERACTION'],
    evidenceLevel: 'C',
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT', 'CYP3A4_SUBSTRATE'],
    commonInSystemTypes: ['TRADITIONAL', 'INTEGRATIVE'],
    traditionalUses: ['Ayurvedic anti-inflammatory', 'Digestive support'],
  },
  {
    slug: 'green-tea-high-dose',
    commonName: 'Green tea extract (high-dose)',
    scientificName: 'Camellia sinensis',
    commonNamePt: 'Chá verde',
    commonNameEs: 'Té verde',
    holdDaysPreOp: 7,
    mechanism: 'EGCG has antiplatelet activity and inhibits CYP3A4 and UGT. Contains vitamin K (whole leaf) — affects warfarin.',
    clinicalConcern: 'Bleeding with antiplatelets; reduced warfarin efficacy due to vitamin K content.',
    primaryRiskCategory: 'BLEEDING',
    riskCategories: ['BLEEDING', 'CYP_INTERACTION'],
    evidenceLevel: 'C',
    interactingMedClasses: ['ANTIPLATELET', 'WARFARIN', 'CYP3A4_SUBSTRATE'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY', 'INTEGRATIVE'],
  },

  // ── Specific interaction risks ───────────────────────────────────────────
  {
    slug: 'yohimbe',
    commonName: 'Yohimbe',
    scientificName: 'Pausinystalia yohimbe',
    commonNamePt: 'Yohimbe',
    commonNameEs: 'Yohimbe',
    holdDaysPreOp: 14,
    mechanism: 'Alpha-2 adrenergic antagonist causing hypertension, tachycardia, and anxiety. Dangerous interactions with MAOIs and sympathomimetics.',
    clinicalConcern: 'Hypertensive crisis, arrhythmia, and MI risk under anesthesia.',
    primaryRiskCategory: 'CARDIOVASCULAR',
    evidenceLevel: 'B',
    interactingMedClasses: ['MAO_INHIBITOR', 'SYMPATHOMIMETIC', 'ANTIHYPERTENSIVE'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY'],
    traditionalUses: ['Erectile dysfunction'],
  },
  {
    slug: 'licorice',
    commonName: 'Licorice root (glycyrrhizin)',
    scientificName: 'Glycyrrhiza glabra',
    commonNamePt: 'Alcaçuz',
    commonNameEs: 'Regaliz',
    holdDaysPreOp: 7,
    mechanism: 'Glycyrrhizin inhibits 11-beta-hydroxysteroid dehydrogenase — pseudo-aldosteronism with hypokalemia, hypertension, and fluid retention.',
    clinicalConcern: 'Electrolyte imbalance (hypokalemia) may precipitate arrhythmia under anesthesia. Avoid in patients on diuretics or digoxin. Does NOT apply to deglycyrrhizinated licorice (DGL).',
    primaryRiskCategory: 'ELECTROLYTE',
    riskCategories: ['ELECTROLYTE', 'CARDIOVASCULAR'],
    evidenceLevel: 'B',
    citationPmid: SPAQI_PMID,
    interactingMedClasses: ['DIURETIC', 'DIGOXIN', 'CORTICOSTEROID'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY'],
    traditionalUses: ['TCM harmonizing herb', 'Gastric ulcers', 'Cough'],
  },
  {
    slug: 'melatonin',
    commonName: 'Melatonin',
    scientificName: 'N-acetyl-5-methoxytryptamine',
    commonNamePt: 'Melatonina',
    commonNameEs: 'Melatonina',
    holdDaysPreOp: 1,
    mechanism: 'Additive sedation with anesthetics; inhibits platelet aggregation at high doses. Emerging evidence supports a pre-anesthetic anxiolytic role.',
    clinicalConcern: 'Stop the day of surgery unless being used for anesthetic pre-medication under physician direction.',
    primaryRiskCategory: 'CNS_SEDATION',
    evidenceLevel: 'B',
    interactingMedClasses: ['BENZODIAZEPINE', 'OPIOID'],
    commonInSystemTypes: ['CONVENTIONAL', 'INTEGRATIVE'],
    traditionalUses: ['Sleep', 'Jet lag'],
  },
  {
    slug: 'chamomile-high-dose',
    commonName: 'Chamomile (concentrated extract)',
    scientificName: 'Matricaria chamomilla',
    commonNamePt: 'Camomila',
    commonNameEs: 'Manzanilla',
    holdDaysPreOp: 7,
    mechanism: 'Contains coumarin derivatives; antiplatelet activity at high supplement doses.',
    clinicalConcern: 'Mild bleeding risk. Tea-level consumption is low risk.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'D',
    interactingMedClasses: ['ANTICOAGULANT', 'ANTIPLATELET'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY'],
    traditionalUses: ['Digestive support', 'Anxiety', 'Sleep'],
  },
  {
    slug: 'hawthorn',
    commonName: 'Hawthorn',
    scientificName: 'Crataegus monogyna',
    commonNamePt: 'Espinheiro-branco',
    commonNameEs: 'Espino blanco',
    holdDaysPreOp: 7,
    mechanism: 'Positive inotropic and vasodilatory effects; enhances cardiac glycoside activity.',
    clinicalConcern: 'Unpredictable hemodynamics; additive effect with digoxin, beta-blockers, and antihypertensives.',
    primaryRiskCategory: 'CARDIOVASCULAR',
    evidenceLevel: 'C',
    interactingMedClasses: ['DIGOXIN', 'BETA_BLOCKER', 'ANTIHYPERTENSIVE', 'NITRATE'],
    commonInSystemTypes: ['COMPLEMENTARY', 'TRADITIONAL'],
    traditionalUses: ['Mild heart failure', 'Hypertension (adjunct)'],
  },
  {
    slug: 'bilberry',
    commonName: 'Bilberry',
    scientificName: 'Vaccinium myrtillus',
    commonNamePt: 'Mirtilo',
    commonNameEs: 'Arándano europeo',
    holdDaysPreOp: 7,
    mechanism: 'Anthocyanosides have antiplatelet and hypoglycemic activity.',
    clinicalConcern: 'Bleeding and hypoglycemia risk.',
    primaryRiskCategory: 'BLEEDING',
    riskCategories: ['BLEEDING', 'GLYCEMIC'],
    evidenceLevel: 'D',
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT', 'HYPOGLYCEMIC'],
    commonInSystemTypes: ['COMPLEMENTARY'],
    traditionalUses: ['Vision support', 'Circulation'],
  },
  {
    slug: 'horse-chestnut',
    commonName: 'Horse chestnut seed extract',
    scientificName: 'Aesculus hippocastanum',
    commonNamePt: 'Castanha-da-índia',
    commonNameEs: 'Castaño de Indias',
    holdDaysPreOp: 7,
    mechanism: 'Aescin reduces capillary permeability; mild antiplatelet effect.',
    clinicalConcern: 'Bleeding risk with anticoagulants.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'C',
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT'],
    commonInSystemTypes: ['COMPLEMENTARY'],
    traditionalUses: ['Chronic venous insufficiency'],
  },
  {
    slug: 'evening-primrose-oil',
    commonName: 'Evening primrose oil',
    scientificName: 'Oenothera biennis',
    commonNamePt: 'Óleo de prímula',
    commonNameEs: 'Aceite de onagra',
    holdDaysPreOp: 7,
    mechanism: 'Gamma-linolenic acid has mild antiplatelet effects; may lower seizure threshold at high doses.',
    clinicalConcern: 'Bleeding risk; seizure risk in epileptic patients.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'D',
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT', 'ANTICONVULSANT'],
    commonInSystemTypes: ['COMPLEMENTARY'],
    traditionalUses: ['Premenstrual syndrome', 'Skin conditions'],
  },

  // ── Low-risk supplements that still warrant disclosure ────────────────────
  {
    slug: 'milk-thistle',
    commonName: 'Milk thistle',
    scientificName: 'Silybum marianum',
    commonNamePt: 'Cardo-mariano',
    commonNameEs: 'Cardo mariano',
    holdDaysPreOp: 0,
    mechanism: 'Silymarin inhibits CYP2C9 and CYP3A4 at high doses; otherwise generally safe.',
    clinicalConcern: 'Disclose to anesthesia; may affect warfarin and other CYP2C9 substrates.',
    primaryRiskCategory: 'CYP_INTERACTION',
    evidenceLevel: 'C',
    interactingMedClasses: ['WARFARIN', 'CYP3A4_SUBSTRATE', 'CYP2C9_SUBSTRATE'],
    commonInSystemTypes: ['COMPLEMENTARY', 'INTEGRATIVE'],
    traditionalUses: ['Liver support'],
    mustDiscloseToAnesthesia: true,
  },
  {
    slug: 'glucosamine',
    commonName: 'Glucosamine',
    scientificName: 'Glucosamine sulfate',
    commonNamePt: 'Glucosamina',
    commonNameEs: 'Glucosamina',
    holdDaysPreOp: 0,
    mechanism: 'May interact with warfarin (increased INR in case reports); possible mild glycemic effect.',
    clinicalConcern: 'Disclose if on warfarin for INR monitoring.',
    primaryRiskCategory: 'OTHER',
    evidenceLevel: 'C',
    interactingMedClasses: ['WARFARIN'],
    commonInSystemTypes: ['CONVENTIONAL', 'COMPLEMENTARY'],
    traditionalUses: ['Osteoarthritis'],
  },
  {
    slug: 'coenzyme-q10',
    commonName: 'Coenzyme Q10',
    scientificName: 'Ubiquinone',
    aliases: ['CoQ10', 'ubiquinol'],
    commonNamePt: 'Coenzima Q10',
    commonNameEs: 'Coenzima Q10',
    holdDaysPreOp: 0,
    mechanism: 'Structural similarity to vitamin K — may antagonize warfarin effect.',
    clinicalConcern: 'Disclose if on warfarin; generally low risk otherwise.',
    primaryRiskCategory: 'OTHER',
    evidenceLevel: 'C',
    interactingMedClasses: ['WARFARIN', 'ANTIHYPERTENSIVE'],
    commonInSystemTypes: ['CONVENTIONAL', 'INTEGRATIVE'],
    traditionalUses: ['Cardiovascular support', 'Statin myopathy'],
  },
  {
    slug: 'aloe-vera-oral',
    commonName: 'Aloe vera (oral / internal)',
    scientificName: 'Aloe barbadensis',
    commonNamePt: 'Babosa',
    commonNameEs: 'Sábila',
    holdDaysPreOp: 7,
    mechanism: 'Anthraquinones in whole-leaf preparations cause laxative-mediated hypokalemia with chronic use.',
    clinicalConcern: 'Hypokalemia risk — arrhythmia under anesthesia, especially with diuretics or digoxin. Topical use is safe.',
    primaryRiskCategory: 'ELECTROLYTE',
    evidenceLevel: 'C',
    interactingMedClasses: ['DIURETIC', 'DIGOXIN', 'LAXATIVE'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY'],
    traditionalUses: ['Digestive support', 'Topical wound care'],
  },
  {
    slug: 'senna',
    commonName: 'Senna',
    scientificName: 'Senna alexandrina',
    commonNamePt: 'Sene',
    commonNameEs: 'Sen',
    holdDaysPreOp: 3,
    mechanism: 'Stimulant laxative causing chronic hypokalemia and dehydration with habitual use.',
    clinicalConcern: 'Electrolyte depletion and volume contraction — arrhythmia and hypotension risk.',
    primaryRiskCategory: 'ELECTROLYTE',
    evidenceLevel: 'C',
    interactingMedClasses: ['DIURETIC', 'DIGOXIN', 'LAXATIVE'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY'],
    traditionalUses: ['Constipation'],
  },
  {
    slug: 'cayenne',
    commonName: 'Cayenne / capsaicin (oral)',
    scientificName: 'Capsicum annuum',
    commonNamePt: 'Pimenta caiena',
    commonNameEs: 'Pimienta de cayena',
    holdDaysPreOp: 7,
    mechanism: 'Mild antiplatelet activity at supplement doses.',
    clinicalConcern: 'Bleeding risk with anticoagulants.',
    primaryRiskCategory: 'BLEEDING',
    evidenceLevel: 'D',
    interactingMedClasses: ['ANTIPLATELET', 'ANTICOAGULANT'],
    commonInSystemTypes: ['TRADITIONAL'],
    traditionalUses: ['Circulation', 'Digestive stimulant'],
  },
  {
    slug: 'passionflower',
    commonName: 'Passionflower',
    scientificName: 'Passiflora incarnata',
    commonNamePt: 'Maracujá (passiflora)',
    commonNameEs: 'Pasiflora',
    holdDaysPreOp: 7,
    mechanism: 'GABA-ergic sedative effect; additive with anesthetics and benzodiazepines.',
    clinicalConcern: 'Prolonged sedation.',
    primaryRiskCategory: 'CNS_SEDATION',
    evidenceLevel: 'C',
    interactingMedClasses: ['BENZODIAZEPINE', 'OPIOID'],
    commonInSystemTypes: ['TRADITIONAL', 'COMPLEMENTARY'],
    traditionalUses: ['Anxiety', 'Insomnia', 'Brazilian folk medicine'],
  },
];

async function main() {
  console.log(`Seeding ${HERBALS.length} herbal contraindications from SPAQI 2020...`);
  let created = 0;
  let updated = 0;

  for (const h of HERBALS) {
    const existing = await prisma.herbalContraindication.findUnique({
      where: { slug: h.slug },
      select: { id: true },
    });

    await prisma.herbalContraindication.upsert({
      where: { slug: h.slug },
      update: {
        commonName: h.commonName,
        scientificName: h.scientificName,
        aliases: h.aliases ?? [],
        commonNamePt: h.commonNamePt ?? null,
        commonNameEs: h.commonNameEs ?? null,
        holdDaysPreOp: h.holdDaysPreOp,
        mechanism: h.mechanism,
        clinicalConcern: h.clinicalConcern,
        primaryRiskCategory: h.primaryRiskCategory,
        riskCategories: h.riskCategories ?? [h.primaryRiskCategory],
        evidenceLevel: h.evidenceLevel ?? 'C',
        citationPmid: h.citationPmid ?? null,
        additionalPmids: h.additionalPmids ?? [],
        interactingMedClasses: h.interactingMedClasses ?? [],
        commonInSystemTypes: h.commonInSystemTypes ?? [],
        traditionalUses: h.traditionalUses ?? [],
        mustDiscloseToAnesthesia: h.mustDiscloseToAnesthesia ?? true,
      },
      create: {
        slug: h.slug,
        commonName: h.commonName,
        scientificName: h.scientificName,
        aliases: h.aliases ?? [],
        commonNamePt: h.commonNamePt ?? null,
        commonNameEs: h.commonNameEs ?? null,
        holdDaysPreOp: h.holdDaysPreOp,
        mechanism: h.mechanism,
        clinicalConcern: h.clinicalConcern,
        primaryRiskCategory: h.primaryRiskCategory,
        riskCategories: h.riskCategories ?? [h.primaryRiskCategory],
        evidenceLevel: h.evidenceLevel ?? 'C',
        citationPmid: h.citationPmid ?? null,
        additionalPmids: h.additionalPmids ?? [],
        interactingMedClasses: h.interactingMedClasses ?? [],
        commonInSystemTypes: h.commonInSystemTypes ?? [],
        traditionalUses: h.traditionalUses ?? [],
        mustDiscloseToAnesthesia: h.mustDiscloseToAnesthesia ?? true,
      },
    });

    if (existing) updated++;
    else created++;
  }

  console.log(`  ${created} created, ${updated} updated (${HERBALS.length} total)`);
}

main()
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
