/**
 * Create Referral API
 *
 * POST /api/prevention/hub/create-referral
 * Creates a specialist referral from prevention recommendations.
 * Referrals are tracked via ProviderTask (until ClinicalReferral model is added).
 *
 * Request Body:
 * - patientId: string (required) - Patient ID
 * - specialty: string (required) - Specialist type (e.g., "Cardiology", "Oncology")
 * - reason: string (required) - Reason for referral
 * - referralType: string (optional, default: 'consultation')
 * - urgency: 'routine' | 'urgent' | 'stat' (optional, default: 'routine')
 * - linkedInterventionId: string (optional) - Link to prevention intervention
 * - notes: string (optional)
 *
 * Phase 5: Hub Actions & Clinical Workflows
 */

import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth/auth';
import { prisma } from '@/lib/prisma';
import logger from '@/lib/logger';
import { z } from 'zod';
import { auditCreate } from '@/lib/audit';

export const dynamic = 'force-dynamic';

// Request validation schema
const CreateReferralSchema = z.object({
  patientId: z.string().min(1, 'patientId is required'),
  specialty: z.string().min(1, 'specialty is required'),
  reason: z.string().min(1, 'reason is required'),
  referralType: z.string().default('consultation'),
  urgency: z.enum(['routine', 'urgent', 'stat']).default('routine'),
  linkedInterventionId: z.string().optional(),
  notes: z.string().optional(),
});

// Map urgency to task priority
const urgencyToTaskPriority = {
  routine: 'NORMAL' as const,
  urgent: 'HIGH' as const,
  stat: 'URGENT' as const,
};

/**
 * POST /api/prevention/hub/create-referral
 * Create a specialist referral
 */
export async function POST(request: NextRequest) {
  const start = performance.now();

  try {
    // Verify authentication
    const session = await auth();

    if (!session?.user?.id) {
      return NextResponse.json(
        { error: 'Unauthorized - Please log in' },
        { status: 401 }
      );
    }

    // Parse and validate request body
    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: 'Invalid JSON in request body' },
        { status: 400 }
      );
    }

    const validation = CreateReferralSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        {
          error: 'Validation failed',
          details: validation.error.errors,
        },
        { status: 400 }
      );
    }

    const { patientId, specialty, reason, referralType, urgency, linkedInterventionId, notes } = validation.data;

    // Verify patient exists
    const patient = await prisma.patient.findUnique({
      where: { id: patientId },
      select: { id: true, firstName: true, lastName: true },
    });

    if (!patient) {
      return NextResponse.json(
        { error: 'Patient not found' },
        { status: 404 }
      );
    }

    // Build description
    const descriptionParts = [
      `Reason: ${reason}`,
      `Patient: ${patient.firstName} ${patient.lastName}`,
      `Referral Type: ${referralType}`,
    ];
    if (notes) {
      descriptionParts.push(`Notes: ${notes}`);
    }

    // Create the referral as a ProviderTask
    const referralTask = await prisma.providerTask.create({
      data: {
        title: `Referral to ${specialty}`,
        description: descriptionParts.join('\n'),
        category: 'FOLLOW_UP',
        priority: urgencyToTaskPriority[urgency],
        status: 'PENDING',
        assignedTo: session.user.id,
        relatedType: 'Patient',
        relatedId: patientId,
        autoGenerated: true,
        generatedBy: 'prevention_hub_referral',
      },
    });

    // If linked to a screening intervention, update the screening
    if (linkedInterventionId) {
      try {
        await prisma.screeningOutcome.update({
          where: { id: linkedInterventionId },
          data: {
            notes: notes
              ? `Referral to ${specialty} placed. Reason: ${reason}. ${notes}`
              : `Referral to ${specialty} placed. Reason: ${reason}`,
          },
        });
      } catch (linkError) {
        // Log but don't fail - the referral is already created
        logger.warn({
          event: 'referral_intervention_link_failed',
          interventionId: linkedInterventionId,
          referralId: referralTask.id,
          error: linkError instanceof Error ? linkError.message : String(linkError),
        });
      }
    }

    const elapsed = performance.now() - start;

    logger.info({
      event: 'referral_created',
      referralId: referralTask.id,
      specialty,
      referralType,
      patientId,
      userId: session.user.id,
      urgency,
      latencyMs: elapsed.toFixed(2),
    });

    // HIPAA Audit
    await auditCreate('Referral', referralTask.id, request, {
      action: 'referral_created',
      specialty,
      referralType,
      reason,
      patientId,
      createdBy: session.user.id,
      urgency,
      linkedInterventionId,
    });

    return NextResponse.json({
      success: true,
      data: {
        referral: {
          id: referralTask.id,
          patientId,
          specialty,
          referralType,
          reason,
          urgency,
          status: 'PENDING',
          linkedInterventionId,
          createdAt: referralTask.createdAt,
        },
      },
      meta: {
        latencyMs: Math.round(elapsed),
      },
    });
  } catch (error) {
    const elapsed = performance.now() - start;

    logger.error({
      event: 'create_referral_error',
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
      latencyMs: elapsed.toFixed(2),
    });

    return NextResponse.json(
      {
        error: 'Failed to create referral',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
