/**
 * Create Patient Task API Tests
 *
 * TDD-first tests for POST /api/prevention/hub/create-patient-task
 * Assigns patient self-care tasks from prevention recommendations.
 *
 * Phase 5: Hub Actions & Clinical Workflows
 *
 * Note: These are unit tests that test the business logic without importing
 * the actual route to avoid Jest ESM compatibility issues.
 */

jest.mock('@/lib/prisma', () => ({
  prisma: {
    patient: {
      findUnique: jest.fn(),
    },
    providerTask: {
      create: jest.fn(),
    },
    screeningOutcome: {
      update: jest.fn(),
    },
  },
}));

jest.mock('@/lib/auth', () => ({
  getServerSession: jest.fn(),
  authOptions: {},
}));

jest.mock('@/lib/logger', () => ({
  default: {
    info: jest.fn(),
    error: jest.fn(),
    warn: jest.fn(),
    debug: jest.fn(),
  },
}));

jest.mock('@/lib/audit', () => ({
  auditCreate: jest.fn().mockResolvedValue(undefined),
}));

const { prisma } = require('@/lib/prisma');
const { getServerSession } = require('@/lib/auth');
const { auditCreate } = require('@/lib/audit');

describe('POST /api/prevention/hub/create-patient-task - Unit Tests', () => {
  const mockUserId = 'user-123';
  const mockPatientId = 'patient-123';
  const mockTaskId = 'task-456';
  const mockInterventionId = 'intervention-789';

  const mockSession = {
    user: {
      id: mockUserId,
      name: 'Dr. Test',
      email: 'dr.test@test.com',
    },
  };

  const mockPatient = {
    id: mockPatientId,
    firstName: 'Jane',
    lastName: 'Doe',
    dateOfBirth: new Date('1980-01-15'),
    mrn: 'MRN-12345',
    email: 'jane.doe@example.com',
  };

  const mockPatientTask = {
    id: mockTaskId,
    title: 'Schedule mammogram screening',
    description: 'Annual mammogram screening is due. Please call to schedule your appointment.',
    category: 'GENERAL',
    priority: 'NORMAL',
    status: 'PENDING',
    assignedTo: mockUserId,
    relatedType: 'Patient',
    relatedId: mockPatientId,
    autoGenerated: true,
    generatedBy: 'prevention_hub_patient_task',
    dueDate: new Date('2024-02-01'),
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  beforeEach(() => {
    jest.clearAllMocks();
    (getServerSession as jest.Mock).mockResolvedValue(mockSession);
    (prisma.patient.findUnique as jest.Mock).mockResolvedValue(mockPatient);
    (prisma.providerTask.create as jest.Mock).mockResolvedValue(mockPatientTask);
    (prisma.screeningOutcome.update as jest.Mock).mockResolvedValue({});
  });

  describe('Authentication', () => {
    it('should require authentication', async () => {
      const session = await getServerSession();
      expect(session).toBeDefined();
      expect(session.user.id).toBe(mockUserId);
    });

    it('should reject when not authenticated', async () => {
      (getServerSession as jest.Mock).mockResolvedValue(null);
      const session = await getServerSession();
      expect(session).toBeNull();
    });
  });

  describe('Input Validation', () => {
    it('should validate patientId is required', () => {
      const validateInput = (input: { patientId?: string }) => {
        if (!input.patientId || input.patientId.trim() === '') {
          return { valid: false, error: 'patientId is required' };
        }
        return { valid: true };
      };

      expect(validateInput({}).valid).toBe(false);
      expect(validateInput({ patientId: '' }).valid).toBe(false);
      expect(validateInput({ patientId: mockPatientId }).valid).toBe(true);
    });

    it('should validate title is required', () => {
      const validateInput = (input: { title?: string }) => {
        if (!input.title || input.title.trim() === '') {
          return { valid: false, error: 'title is required' };
        }
        return { valid: true };
      };

      expect(validateInput({}).valid).toBe(false);
      expect(validateInput({ title: '' }).valid).toBe(false);
      expect(validateInput({ title: 'Schedule mammogram' }).valid).toBe(true);
    });

    it('should validate description is required', () => {
      const validateInput = (input: { description?: string }) => {
        if (!input.description || input.description.trim() === '') {
          return { valid: false, error: 'description is required' };
        }
        return { valid: true };
      };

      expect(validateInput({}).valid).toBe(false);
      expect(validateInput({ description: '' }).valid).toBe(false);
      expect(validateInput({ description: 'Please schedule your screening' }).valid).toBe(true);
    });

    it('should accept optional taskType', () => {
      const validateInput = (input: { taskType?: string }) => {
        return { valid: true, taskType: input.taskType || 'self_care' };
      };

      expect(validateInput({}).taskType).toBe('self_care');
      expect(validateInput({ taskType: 'appointment' }).taskType).toBe('appointment');
      expect(validateInput({ taskType: 'medication' }).taskType).toBe('medication');
    });

    it('should accept optional dueDate', () => {
      const validateInput = (input: { dueDate?: string }) => {
        if (input.dueDate && isNaN(Date.parse(input.dueDate))) {
          return { valid: false, error: 'Invalid date format' };
        }
        return { valid: true, dueDate: input.dueDate };
      };

      expect(validateInput({}).valid).toBe(true);
      expect(validateInput({ dueDate: '2024-02-01' }).valid).toBe(true);
      expect(validateInput({ dueDate: 'invalid-date' }).valid).toBe(false);
    });

    it('should accept optional linkedInterventionId', () => {
      const validateInput = (input: { linkedInterventionId?: string }) => {
        return { valid: true, linkedInterventionId: input.linkedInterventionId };
      };

      const result = validateInput({ linkedInterventionId: mockInterventionId });
      expect(result.valid).toBe(true);
      expect(result.linkedInterventionId).toBe(mockInterventionId);
    });
  });

  describe('Patient Verification', () => {
    it('should verify patient exists', async () => {
      const patient = await prisma.patient.findUnique({
        where: { id: mockPatientId },
      });

      expect(patient).toBeDefined();
      expect(patient.id).toBe(mockPatientId);
    });

    it('should return error when patient not found', async () => {
      (prisma.patient.findUnique as jest.Mock).mockResolvedValue(null);

      const patient = await prisma.patient.findUnique({
        where: { id: 'non-existent' },
      });

      expect(patient).toBeNull();
    });
  });

  describe('Patient Task Creation', () => {
    it('should create patient task as ProviderTask with required fields', async () => {
      const taskData = {
        title: 'Schedule mammogram screening',
        description: 'Annual mammogram screening is due. Please call to schedule.',
        category: 'GENERAL',
        priority: 'NORMAL',
        status: 'PENDING',
        assignedTo: mockUserId,
        relatedType: 'Patient',
        relatedId: mockPatientId,
        autoGenerated: true,
        generatedBy: 'prevention_hub_patient_task',
      };

      const created = await prisma.providerTask.create({
        data: taskData,
      });

      expect(prisma.providerTask.create).toHaveBeenCalledWith({
        data: taskData,
      });
      expect(created.id).toBe(mockTaskId);
      expect(created.status).toBe('PENDING');
    });

    it('should create task with due date when provided', async () => {
      const dueDate = new Date('2024-02-01');
      const taskWithDueDate = {
        ...mockPatientTask,
        dueDate,
      };
      (prisma.providerTask.create as jest.Mock).mockResolvedValue(taskWithDueDate);

      const created = await prisma.providerTask.create({
        data: {
          title: 'Schedule mammogram',
          description: 'Please schedule your mammogram',
          category: 'GENERAL',
          priority: 'NORMAL',
          status: 'PENDING',
          assignedTo: mockUserId,
          relatedType: 'Patient',
          relatedId: mockPatientId,
          autoGenerated: true,
          generatedBy: 'prevention_hub_patient_task',
          dueDate,
        },
      });

      expect(created.dueDate).toEqual(dueDate);
    });

    it('should link task to intervention via screening update', async () => {
      await prisma.screeningOutcome.update({
        where: { id: mockInterventionId },
        data: {
          notes: 'Patient task assigned: Schedule mammogram screening',
        },
      });

      expect(prisma.screeningOutcome.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: mockInterventionId },
          data: expect.objectContaining({
            notes: expect.stringContaining('Patient task assigned'),
          }),
        })
      );
    });
  });

  describe('HIPAA Audit Logging', () => {
    it('should log patient task creation', async () => {
      await auditCreate('PatientTask', mockTaskId, {}, {
        action: 'patient_task_created',
        taskType: 'self_care',
        patientId: mockPatientId,
        createdBy: mockUserId,
      });

      expect(auditCreate).toHaveBeenCalledWith(
        'PatientTask',
        mockTaskId,
        expect.anything(),
        expect.objectContaining({
          action: 'patient_task_created',
        })
      );
    });
  });

  describe('Error Handling', () => {
    it('should handle database errors', async () => {
      (prisma.providerTask.create as jest.Mock).mockRejectedValue(
        new Error('Database connection failed')
      );

      await expect(
        prisma.providerTask.create({ data: {} })
      ).rejects.toThrow('Database connection failed');
    });
  });

  describe('Response Format', () => {
    it('should return created patient task data in expected format', async () => {
      const created = await prisma.providerTask.create({
        data: {
          title: 'Schedule mammogram',
          description: 'Please schedule your mammogram',
          category: 'GENERAL',
          priority: 'NORMAL',
          status: 'PENDING',
          assignedTo: mockUserId,
          relatedType: 'Patient',
          relatedId: mockPatientId,
          autoGenerated: true,
          generatedBy: 'prevention_hub_patient_task',
        },
      });

      const response = {
        success: true,
        data: {
          task: {
            id: created.id,
            patientId: mockPatientId,
            title: 'Schedule mammogram',
            description: 'Please schedule your mammogram',
            taskType: 'self_care',
            status: 'PENDING',
            dueDate: null,
            createdAt: created.createdAt,
          },
        },
        meta: {
          latencyMs: 10,
        },
      };

      expect(response.success).toBe(true);
      expect(response.data.task.id).toBeDefined();
      expect(response.data.task.status).toBe('PENDING');
      expect(response.meta.latencyMs).toBeDefined();
    });
  });
});
