/**
 * ClinicalSafetyEnvelope — standard wrapper for all CDSS responses.
 * Every route that returns clinical decision support data must wrap
 * its response in this envelope to ensure:
 * - Provenance tracking (which model, when)
 * - Processing method transparency (AI vs deterministic)
 * - Confidence scoring
 * - Standard disclaimer text
 * - Fallback status
 */

export interface ClinicalSafetyEnvelope<T> {
  data: T;
  processingMethod: 'ai' | 'deterministic' | 'hybrid';
  confidence: number; // 0.0 to 1.0
  disclaimer: string;
  fallbackUsed: boolean;
  provenance: {
    model: string;
    version: string;
    timestamp: string;
  };
}

export const CLINICAL_DISCLAIMER =
  'This information is generated by a Clinical Decision Support (CDS) system and is intended to assist healthcare professionals. ' +
  'It does NOT constitute a medical diagnosis, treatment recommendation, or substitute for professional clinical judgment. ' +
  'The treating physician retains full responsibility for all clinical decisions. ' +
  'Always verify against current clinical guidelines and patient-specific factors.';

export function wrapInSafetyEnvelope<T>(
  data: T,
  options: {
    processingMethod: 'ai' | 'deterministic' | 'hybrid';
    confidence: number;
    fallbackUsed: boolean;
    model: string;
    version?: string;
  }
): ClinicalSafetyEnvelope<T> {
  return {
    data,
    processingMethod: options.processingMethod,
    confidence: Math.max(0, Math.min(1, options.confidence)),
    disclaimer: CLINICAL_DISCLAIMER,
    fallbackUsed: options.fallbackUsed,
    provenance: {
      model: options.model,
      version: options.version || '1.0.0',
      timestamp: new Date().toISOString(),
    },
  };
}
