name: holi-labs
region: nyc
domains:
  - domain: holilabs.xyz
    type: PRIMARY
  - domain: www.holilabs.xyz
    type: ALIAS

services:
  - name: web
    github:
      repo: HolisticHealthcareLabs/holilabs
      branch: main
      deploy_on_push: true

    build_command: |
      cd apps/web
      pnpm install --frozen-lockfile
      pnpm prisma generate
      pnpm build

    run_command: cd apps/web && pnpm start

    environment_slug: node-js

    instance_count: 1
    instance_size_slug: basic-xxs

    http_port: 3000

    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    routes:
      - path: /

    envs:
      # App Configuration
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME

      - key: NEXT_PUBLIC_APP_URL
        value: https://holilabs.xyz
        scope: RUN_AND_BUILD_TIME

      - key: NEXTAUTH_URL
        value: https://holilabs.xyz
        scope: RUN_AND_BUILD_TIME

      # Database (SET THIS IN DIGITALOCEAN DASHBOARD)
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # Security Secrets (SET THESE IN DIGITALOCEAN DASHBOARD)
      - key: NEXTAUTH_SECRET
        value: ${NEXTAUTH_SECRET}
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: SESSION_SECRET
        value: ${SESSION_SECRET}
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: ENCRYPTION_KEY
        value: ${ENCRYPTION_KEY}
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: ENCRYPTION_MASTER_KEY
        value: ${ENCRYPTION_MASTER_KEY}
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: CRON_SECRET
        value: ${CRON_SECRET}
        scope: RUN_TIME
        type: SECRET

      - key: JWT_SECRET
        value: ${JWT_SECRET}
        scope: RUN_TIME
        type: SECRET

      - key: JWT_PRIVATE_KEY
        value: ${JWT_PRIVATE_KEY}
        scope: RUN_TIME
        type: SECRET

      - key: SALT_ROTATION_KEY
        value: ${SALT_ROTATION_KEY}
        scope: RUN_TIME
        type: SECRET

      - key: DEID_SECRET
        value: ${DEID_SECRET}
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # AI Services
      - key: ANTHROPIC_API_KEY
        value: ${ANTHROPIC_API_KEY}
        scope: RUN_TIME
        type: SECRET

      - key: GOOGLE_AI_API_KEY
        value: ${GOOGLE_AI_API_KEY}
        scope: RUN_TIME
        type: SECRET

      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        scope: RUN_TIME
        type: SECRET

      - key: ASSEMBLYAI_API_KEY
        value: ${ASSEMBLYAI_API_KEY}
        scope: RUN_TIME
        type: SECRET

      - key: DEEPGRAM_API_KEY
        value: ${DEEPGRAM_API_KEY}
        scope: RUN_TIME
        type: SECRET

      # Email
      - key: RESEND_API_KEY
        value: ${RESEND_API_KEY}
        scope: RUN_TIME
        type: SECRET

      - key: RESEND_FROM_EMAIL
        value: notifications@holilabs.xyz
        scope: RUN_TIME

      # Push Notifications
      - key: NEXT_PUBLIC_VAPID_PUBLIC_KEY
        value: BPgdD0ETGgvkFq0yV3jyRcIoq725bXPbytjUQxmO5LQt5OOG4GH5bx9hyLf5Vr3m9bnzKIwAnyEciPqaK87qalw
        scope: RUN_AND_BUILD_TIME

      - key: VAPID_PRIVATE_KEY
        value: ${VAPID_PRIVATE_KEY}
        scope: RUN_TIME
        type: SECRET

      - key: VAPID_EMAIL
        value: mailto:notifications@holilabs.xyz
        scope: RUN_TIME

      # Twilio (optional)
      - key: TWILIO_ACCOUNT_SID
        value: ${TWILIO_ACCOUNT_SID}
        scope: RUN_TIME
        type: SECRET

      - key: TWILIO_AUTH_TOKEN
        value: ${TWILIO_AUTH_TOKEN}
        scope: RUN_TIME
        type: SECRET

      - key: TWILIO_PHONE_NUMBER
        value: ${TWILIO_PHONE_NUMBER}
        scope: RUN_TIME

      - key: TWILIO_WHATSAPP_NUMBER
        value: ${TWILIO_WHATSAPP_NUMBER}
        scope: RUN_TIME

      # Redis (Upstash)
      - key: UPSTASH_REDIS_REST_URL
        value: ${UPSTASH_REDIS_REST_URL}
        scope: RUN_TIME
        type: SECRET

      - key: UPSTASH_REDIS_REST_TOKEN
        value: ${UPSTASH_REDIS_REST_TOKEN}
        scope: RUN_TIME
        type: SECRET

      # Cloud Storage (R2)
      - key: R2_ENDPOINT
        value: ${R2_ENDPOINT}
        scope: RUN_TIME
        type: SECRET

      - key: R2_BUCKET
        value: ${R2_BUCKET}
        scope: RUN_TIME

      - key: R2_ACCESS_KEY_ID
        value: ${R2_ACCESS_KEY_ID}
        scope: RUN_TIME
        type: SECRET

      - key: R2_SECRET_ACCESS_KEY
        value: ${R2_SECRET_ACCESS_KEY}
        scope: RUN_TIME
        type: SECRET

      # Admin API
      - key: ADMIN_API_KEY
        value: ${ADMIN_API_KEY}
        scope: RUN_TIME
        type: SECRET

      # Search (Meilisearch)
      - key: MEILI_MASTER_KEY
        value: ${MEILI_MASTER_KEY}
        scope: RUN_TIME
        type: SECRET

      # Logging (Logtail/BetterStack)
      - key: LOGTAIL_SOURCE_TOKEN
        value: ${LOGTAIL_SOURCE_TOKEN}
        scope: RUN_TIME
        type: SECRET

      # Analytics (PostHog)
      - key: NEXT_PUBLIC_POSTHOG_KEY
        value: ${NEXT_PUBLIC_POSTHOG_KEY}
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: NEXT_PUBLIC_POSTHOG_HOST
        value: https://us.i.posthog.com
        scope: RUN_AND_BUILD_TIME

      # Next.js Configuration
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
        scope: RUN_AND_BUILD_TIME

      # AI Configuration
      - key: AI_CACHE_ENABLED
        value: "true"
        scope: RUN_TIME
