/**
 * CDSS V3 - Prevention Alert Schema
 *
 * Zod schema for type-safe prevention alert validation.
 * Used by PreventionService to validate alert output.
 */

import { z } from 'zod';

/**
 * Prevention Alert Types
 */
export const PreventionAlertType = z.enum([
  'drug_interaction',
  'screening_overdue',
  'screening_due',
  'critical_lab',
  'recent_hospitalization',
]);

export type PreventionAlertType = z.infer<typeof PreventionAlertType>;

/**
 * Alert Severity Levels
 */
export const AlertSeverity = z.enum(['critical', 'warning', 'info']);

export type AlertSeverity = z.infer<typeof AlertSeverity>;

/**
 * Alert Action Types
 */
export const AlertActionType = z.enum(['order', 'alert', 'link', 'dismiss']);

export type AlertActionType = z.infer<typeof AlertActionType>;

/**
 * Alert Action Schema
 *
 * Defines the action that can be taken on an alert.
 */
export const AlertActionSchema = z.object({
  /** Button/link label (e.g., "Order Colonoscopy") */
  label: z.string().trim().min(1, 'Action label is required').max(50),
  /** Type of action */
  type: AlertActionType,
  /** Additional data for the action */
  payload: z.record(z.string()).optional(),
});

export type AlertAction = z.infer<typeof AlertActionSchema>;

/**
 * Prevention Alert Schema
 *
 * Validates prevention alerts generated by the CDSS.
 * All alerts MUST be validated before returning to the frontend.
 */
export const PreventionAlertSchema = z.object({
  /** Unique identifier for the alert */
  id: z.string().trim().min(1, 'Alert ID is required'),
  /** Type of prevention alert */
  type: PreventionAlertType,
  /** Severity level */
  severity: AlertSeverity,
  /** Short title (max 100 chars) */
  title: z.string().trim().min(1, 'Alert title is required').max(100),
  /** Description of the alert (max 500 chars) */
  description: z.string().trim().min(1, 'Description is required').max(500),
  /** Optional action the user can take */
  action: AlertActionSchema.optional(),
  /** Source of the recommendation (e.g., "USPSTF Grade A") */
  source: z.string().trim().min(1, 'Source is required'),
  /** When the alert was created */
  createdAt: z.date(),
});

export type PreventionAlert = z.infer<typeof PreventionAlertSchema>;

/**
 * Array of Prevention Alerts Schema
 */
export const PreventionAlertsSchema = z.array(PreventionAlertSchema);

export type PreventionAlerts = z.infer<typeof PreventionAlertsSchema>;

/**
 * Partial Prevention Alert Schema (for updates)
 */
export const PartialPreventionAlertSchema = PreventionAlertSchema.partial();

export type PartialPreventionAlert = z.infer<typeof PartialPreventionAlertSchema>;
