/**
 * Provider Task Management API
 *
 * GET /api/tasks - List tasks with filters
 * POST /api/tasks - Create new task
 *
 * RBAC: Requires authenticated clinician/admin session.
 * Uses createProtectedRoute to enforce CYRUS invariant.
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import logger from '@/lib/logger';
import { emitTaskCreatedEvent } from '@/lib/socket-server';
import { createProtectedRoute, type ApiContext } from '@/lib/api/middleware';

export const dynamic = 'force-dynamic';

/**
 * GET /api/tasks
 * List tasks with smart filtering for optimal UX
 */
async function handleGET(request: NextRequest, context: ApiContext) {
  const { searchParams } = new URL(request.url);
  const userId = context.user!.id; // From authenticated session — NOT query params

  // Filters for excellent UX
  const view = searchParams.get('view') || 'today'; // today, week, all, overdue
  const priority = searchParams.get('priority'); // URGENT, HIGH, NORMAL, LOW
  const category = searchParams.get('category');
  const status = searchParams.get('status') || 'PENDING'; // PENDING, IN_PROGRESS, COMPLETED, DISMISSED

  // Build smart date filters based on view
  const now = new Date();
  let dateFilter = {};

  if (view === 'today') {
    const endOfDay = new Date(now);
    endOfDay.setHours(23, 59, 59, 999);
    dateFilter = {
      OR: [
        { dueDate: { lte: endOfDay } },
        { dueDate: null }, // Include undated tasks in "today" view
      ],
    };
  } else if (view === 'week') {
    const endOfWeek = new Date(now);
    endOfWeek.setDate(now.getDate() + 7);
    dateFilter = {
      dueDate: { lte: endOfWeek },
    };
  } else if (view === 'overdue') {
    dateFilter = {
      dueDate: { lt: now },
      status: { in: ['PENDING', 'IN_PROGRESS'] },
    };
  }

  // Build where clause
  const where: any = {
    assignedTo: userId,
    ...(status !== 'all' && { status }),
    ...(priority && { priority }),
    ...(category && { category }),
    ...dateFilter,
  };

  // Get tasks with related data
  const tasks = await prisma.providerTask.findMany({
    where,
    orderBy: [
      { priority: 'desc' }, // URGENT first
      { dueDate: 'asc' },  // Earliest due date first
      { createdAt: 'desc' }, // Newest first if no due date
    ],
    take: 100, // Limit for performance
  });

  // Get counts for each view (for UX badges)
  const [todayCount, overdueCount, allPendingCount] = await Promise.all([
    prisma.providerTask.count({
      where: {
        assignedTo: userId,
        status: { in: ['PENDING', 'IN_PROGRESS'] },
        OR: [
          { dueDate: { lte: new Date(now.setHours(23, 59, 59, 999)) } },
          { dueDate: null },
        ],
      },
    }),
    prisma.providerTask.count({
      where: {
        assignedTo: userId,
        status: { in: ['PENDING', 'IN_PROGRESS'] },
        dueDate: { lt: now },
      },
    }),
    prisma.providerTask.count({
      where: {
        assignedTo: userId,
        status: { in: ['PENDING', 'IN_PROGRESS'] },
      },
    }),
  ]);

  logger.info({
    event: 'tasks_retrieved',
    count: tasks.length,
    view,
    userId,
  });

  return NextResponse.json({
    success: true,
    data: tasks,
    counts: {
      today: todayCount,
      overdue: overdueCount,
      all: allPendingCount,
    },
  });
}

/**
 * POST /api/tasks
 * Create a new task
 */
async function handlePOST(request: NextRequest, context: ApiContext) {
  const body = await request.json();
  const { title, description, category, priority, dueDate, assignedTo, relatedType, relatedId } = body;

  // Validation
  if (!title || !category) {
    return NextResponse.json(
      {
        success: false,
        error: 'Missing required fields: title, category',
      },
      { status: 400 }
    );
  }

  // Default assignedTo to the current authenticated user
  const targetUser = assignedTo || context.user!.id;

  // Create task
  const task = await prisma.providerTask.create({
    data: {
      title,
      description,
      category,
      priority: priority || 'NORMAL',
      assignedTo: targetUser,
      dueDate: dueDate ? new Date(dueDate) : null,
      relatedType,
      relatedId,
      autoGenerated: false,
    },
  });

  logger.info({
    event: 'task_created',
    taskId: task.id,
    category: task.category,
    priority: task.priority,
    createdBy: context.user!.id,
  });

  // Real-time Socket.IO broadcast for task creation
  emitTaskCreatedEvent({
    id: task.id,
    title: task.title,
    category: task.category,
    priority: task.priority as 'URGENT' | 'HIGH' | 'NORMAL' | 'LOW',
    status: task.status as 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'DISMISSED',
    assignedTo: task.assignedTo,
    dueDate: task.dueDate ?? undefined,
    relatedType: task.relatedType ?? undefined,
    relatedId: task.relatedId ?? undefined,
    userId: targetUser,
  });

  return NextResponse.json({
    success: true,
    data: task,
  }, { status: 201 });
}

// Protected route exports with RBAC guard
export const GET = createProtectedRoute(handleGET, {
  roles: ['ADMIN', 'CLINICIAN', 'PHYSICIAN', 'NURSE', 'STAFF'],
  skipCsrf: true,
  audit: { action: 'VIEW', resource: 'ProviderTask' },
});

export const POST = createProtectedRoute(handlePOST, {
  roles: ['ADMIN', 'CLINICIAN', 'PHYSICIAN', 'NURSE', 'STAFF'],
  audit: { action: 'CREATE', resource: 'ProviderTask' },
});
