/**
 * Create Order API
 *
 * POST /api/prevention/hub/create-order
 * Creates a clinical order (lab, imaging, procedure) from prevention recommendations.
 * Orders are tracked via ProviderTask for now (until Order model is added).
 *
 * Request Body:
 * - patientId: string (required) - Patient ID
 * - orderType: 'lab' | 'imaging' | 'procedure' (required)
 * - orderDetails: { code: string, display: string } (required)
 * - priority: 'routine' | 'urgent' | 'stat' (optional, default: 'routine')
 * - linkedInterventionId: string (optional) - Link to prevention intervention
 * - notes: string (optional)
 *
 * Phase 5: Hub Actions & Clinical Workflows
 */

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession, authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import logger from '@/lib/logger';
import { z } from 'zod';
import { auditCreate } from '@/lib/audit';

export const dynamic = 'force-dynamic';

// Request validation schema
const CreateOrderSchema = z.object({
  patientId: z.string().min(1, 'patientId is required'),
  orderType: z.enum(['lab', 'imaging', 'procedure'], {
    errorMap: () => ({ message: 'orderType must be lab, imaging, or procedure' }),
  }),
  orderDetails: z.object({
    code: z.string().min(1, 'orderDetails.code is required'),
    display: z.string().min(1, 'orderDetails.display is required'),
  }),
  priority: z.enum(['routine', 'urgent', 'stat']).default('routine'),
  linkedInterventionId: z.string().optional(),
  notes: z.string().optional(),
});

// Map order type to task category
const orderTypeToTaskCategory = {
  lab: 'LAB_RESULT' as const,
  imaging: 'REVIEW' as const,
  procedure: 'FOLLOW_UP' as const,
};

// Map priority to task priority
const priorityToTaskPriority = {
  routine: 'NORMAL' as const,
  urgent: 'HIGH' as const,
  stat: 'URGENT' as const,
};

/**
 * POST /api/prevention/hub/create-order
 * Create a clinical order
 */
export async function POST(request: NextRequest) {
  const start = performance.now();

  try {
    // Verify authentication
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json(
        { error: 'Unauthorized - Please log in' },
        { status: 401 }
      );
    }

    // Parse and validate request body
    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: 'Invalid JSON in request body' },
        { status: 400 }
      );
    }

    const validation = CreateOrderSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        {
          error: 'Validation failed',
          details: validation.error.errors,
        },
        { status: 400 }
      );
    }

    const { patientId, orderType, orderDetails, priority, linkedInterventionId, notes } = validation.data;

    // Verify patient exists
    const patient = await prisma.patient.findUnique({
      where: { id: patientId },
      select: { id: true, firstName: true, lastName: true },
    });

    if (!patient) {
      return NextResponse.json(
        { error: 'Patient not found' },
        { status: 404 }
      );
    }

    // Create the order as a ProviderTask (until proper Order model exists)
    const orderTask = await prisma.providerTask.create({
      data: {
        title: `${orderType.toUpperCase()} Order: ${orderDetails.display}`,
        description: notes || `Order code: ${orderDetails.code}\nPatient: ${patient.firstName} ${patient.lastName}`,
        category: orderTypeToTaskCategory[orderType],
        priority: priorityToTaskPriority[priority],
        status: 'PENDING',
        assignedTo: session.user.id,
        relatedType: 'Patient',
        relatedId: patientId,
        autoGenerated: true,
        generatedBy: 'prevention_hub_order',
      },
    });

    // If linked to a screening intervention, update the screening
    if (linkedInterventionId) {
      try {
        await prisma.screeningOutcome.update({
          where: { id: linkedInterventionId },
          data: {
            notes: notes
              ? `Order placed: ${orderDetails.display}. ${notes}`
              : `Order placed: ${orderDetails.display}`,
          },
        });
      } catch (linkError) {
        // Log but don't fail - the order is already created
        logger.warn({
          event: 'order_intervention_link_failed',
          interventionId: linkedInterventionId,
          orderId: orderTask.id,
          error: linkError instanceof Error ? linkError.message : String(linkError),
        });
      }
    }

    const elapsed = performance.now() - start;

    logger.info({
      event: 'order_created',
      orderId: orderTask.id,
      orderType,
      orderCode: orderDetails.code,
      patientId,
      userId: session.user.id,
      priority,
      latencyMs: elapsed.toFixed(2),
    });

    // HIPAA Audit
    await auditCreate('Order', orderTask.id, request, {
      action: 'order_created',
      orderType,
      orderCode: orderDetails.code,
      patientId,
      createdBy: session.user.id,
      priority,
      linkedInterventionId,
    });

    return NextResponse.json({
      success: true,
      data: {
        order: {
          id: orderTask.id,
          patientId,
          orderType,
          orderCode: orderDetails.code,
          orderDisplay: orderDetails.display,
          status: 'PENDING',
          priority,
          linkedInterventionId,
          createdAt: orderTask.createdAt,
        },
      },
      meta: {
        latencyMs: Math.round(elapsed),
      },
    });
  } catch (error) {
    const elapsed = performance.now() - start;

    logger.error({
      event: 'create_order_error',
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
      latencyMs: elapsed.toFixed(2),
    });

    return NextResponse.json(
      {
        error: 'Failed to create order',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
