// Type declaration to resolve React version conflicts with lucide-react
declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';

  export type LucideProps = SVGProps<SVGSVGElement>;
  export type LucideIcon = FC<LucideProps>;

  export const Activity: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const Award: LucideIcon;
  export const BarChart3: LucideIcon;
  export const Brain: LucideIcon;
  export const Calendar: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCheck: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const Circle: LucideIcon;
  export const Clock: LucideIcon;
  export const Contrast: LucideIcon;
  export const CornerDownRight: LucideIcon;
  export const Crosshair: LucideIcon;
  export const Copy: LucideIcon;
  export const Download: LucideIcon;
  export const Edit: LucideIcon;
  export const Edit2: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Eye: LucideIcon;
  export const FileEdit: LucideIcon;
  export const FileImage: LucideIcon;
  export const FileText: LucideIcon;
  export const Filter: LucideIcon;
  export const Flag: LucideIcon;
  export const GitCompare: LucideIcon;
  export const Grid3X3: LucideIcon;
  export const Info: LucideIcon;
  export const Loader2: LucideIcon;
  export const Lock: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const Maximize2: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Minimize2: LucideIcon;
  export const Minus: LucideIcon;
  export const Move: LucideIcon;
  export const Pause: LucideIcon;
  export const Play: LucideIcon;
  export const Plus: LucideIcon;
  export const QrCode: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const RotateCw: LucideIcon;
  export const Ruler: LucideIcon;
  export const Save: LucideIcon;
  export const Search: LucideIcon;
  export const Share2: LucideIcon;
  export const Shield: LucideIcon;
  export const Square: LucideIcon;
  export const Star: LucideIcon;
  export const Stethoscope: LucideIcon;
  export const Sun: LucideIcon;
  export const Target: LucideIcon;
  export const ThumbsDown: LucideIcon;
  export const ThumbsUp: LucideIcon;
  export const Trash2: LucideIcon;
  export const TrendingDown: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Upload: LucideIcon;
  export const User: LucideIcon;
  export const X: LucideIcon;
  export const XCircle: LucideIcon;
  export const ZoomIn: LucideIcon;
  export const ZoomOut: LucideIcon;
}
