-- NOTE:
-- This migration was accidentally generated by `prisma migrate dev` on a drifted DB.
-- It contained destructive operations and failed to apply (index/constraint conflicts).
--
-- We keep the migration *directory* so Prisma's migration history stays consistent,
-- but intentionally make the SQL a no-op.

SELECT 1;

