/**
 * Create Referral API Tests
 *
 * TDD-first tests for POST /api/prevention/hub/create-referral
 * Creates specialist referrals from prevention recommendations.
 *
 * Phase 5: Hub Actions & Clinical Workflows
 *
 * Note: These are unit tests that test the business logic without importing
 * the actual route to avoid Jest ESM compatibility issues.
 */

import { describe, it, expect, beforeEach, jest } from '@jest/globals';

// Type helper for jest mocks with @jest/globals
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyMock = jest.Mock<any>;

jest.mock('@/lib/prisma', () => ({
  prisma: {
    patient: {
      findUnique: jest.fn(),
    },
    providerTask: {
      create: jest.fn(),
    },
    screeningOutcome: {
      update: jest.fn(),
    },
  },
}));

jest.mock('@/lib/auth', () => ({
  getServerSession: jest.fn(),
  authOptions: {},
}));

jest.mock('@/lib/logger', () => ({
  default: {
    info: jest.fn(),
    error: jest.fn(),
    warn: jest.fn(),
    debug: jest.fn(),
  },
}));

jest.mock('@/lib/audit', () => ({
  auditCreate: jest.fn(() => Promise.resolve(undefined)),
}));

const { prisma } = require('@/lib/prisma');
const { getServerSession } = require('@/lib/auth');
const { auditCreate } = require('@/lib/audit');

describe('POST /api/prevention/hub/create-referral - Unit Tests', () => {
  const mockUserId = 'user-123';
  const mockPatientId = 'patient-123';
  const mockReferralId = 'referral-456';
  const mockInterventionId = 'intervention-789';

  const mockSession = {
    user: {
      id: mockUserId,
      name: 'Dr. Test',
      email: 'dr.test@test.com',
    },
  };

  const mockPatient = {
    id: mockPatientId,
    firstName: 'Jane',
    lastName: 'Doe',
    dateOfBirth: new Date('1980-01-15'),
    mrn: 'MRN-12345',
  };

  const mockReferralTask = {
    id: mockReferralId,
    title: 'Referral to Cardiology',
    description: 'Reason: High cardiovascular risk - ASCVD 12.5%\nPatient: Jane Doe',
    category: 'FOLLOW_UP',
    priority: 'NORMAL',
    status: 'PENDING',
    assignedTo: mockUserId,
    relatedType: 'Patient',
    relatedId: mockPatientId,
    autoGenerated: true,
    generatedBy: 'prevention_hub_referral',
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  beforeEach(() => {
    jest.clearAllMocks();
    (getServerSession as AnyMock).mockResolvedValue(mockSession);
    (prisma.patient.findUnique as AnyMock).mockResolvedValue(mockPatient);
    (prisma.providerTask.create as AnyMock).mockResolvedValue(mockReferralTask);
    (prisma.screeningOutcome.update as AnyMock).mockResolvedValue({});
  });

  describe('Authentication', () => {
    it('should require authentication', async () => {
      const session = await getServerSession();
      expect(session).toBeDefined();
      expect(session.user.id).toBe(mockUserId);
    });

    it('should reject when not authenticated', async () => {
      (getServerSession as AnyMock).mockResolvedValue(null);
      const session = await getServerSession();
      expect(session).toBeNull();
    });
  });

  describe('Input Validation', () => {
    it('should validate patientId is required', () => {
      const validateInput = (input: { patientId?: string }) => {
        if (!input.patientId || input.patientId.trim() === '') {
          return { valid: false, error: 'patientId is required' };
        }
        return { valid: true };
      };

      expect(validateInput({}).valid).toBe(false);
      expect(validateInput({ patientId: '' }).valid).toBe(false);
      expect(validateInput({ patientId: mockPatientId }).valid).toBe(true);
    });

    it('should validate specialty is required', () => {
      const validateInput = (input: { specialty?: string }) => {
        if (!input.specialty || input.specialty.trim() === '') {
          return { valid: false, error: 'specialty is required' };
        }
        return { valid: true };
      };

      expect(validateInput({}).valid).toBe(false);
      expect(validateInput({ specialty: '' }).valid).toBe(false);
      expect(validateInput({ specialty: 'Cardiology' }).valid).toBe(true);
    });

    it('should validate reason is required', () => {
      const validateInput = (input: { reason?: string }) => {
        if (!input.reason || input.reason.trim() === '') {
          return { valid: false, error: 'reason is required' };
        }
        return { valid: true };
      };

      expect(validateInput({}).valid).toBe(false);
      expect(validateInput({ reason: '' }).valid).toBe(false);
      expect(validateInput({ reason: 'High cardiovascular risk' }).valid).toBe(true);
    });

    it('should validate urgency if provided', () => {
      const validateInput = (input: { urgency?: string }) => {
        const validUrgencies = ['routine', 'urgent', 'stat'];
        if (input.urgency && !validUrgencies.includes(input.urgency)) {
          return { valid: false, error: 'urgency must be routine, urgent, or stat' };
        }
        return { valid: true, urgency: input.urgency || 'routine' };
      };

      expect(validateInput({}).urgency).toBe('routine');
      expect(validateInput({ urgency: 'routine' }).valid).toBe(true);
      expect(validateInput({ urgency: 'urgent' }).valid).toBe(true);
      expect(validateInput({ urgency: 'stat' }).valid).toBe(true);
      expect(validateInput({ urgency: 'invalid' }).valid).toBe(false);
    });

    it('should accept optional referralType', () => {
      const validateInput = (input: { referralType?: string }) => {
        return { valid: true, referralType: input.referralType || 'consultation' };
      };

      expect(validateInput({}).referralType).toBe('consultation');
      expect(validateInput({ referralType: 'evaluation' }).referralType).toBe('evaluation');
    });

    it('should accept optional linkedInterventionId', () => {
      const validateInput = (input: { linkedInterventionId?: string }) => {
        return { valid: true, linkedInterventionId: input.linkedInterventionId };
      };

      const result = validateInput({ linkedInterventionId: mockInterventionId });
      expect(result.valid).toBe(true);
      expect(result.linkedInterventionId).toBe(mockInterventionId);
    });
  });

  describe('Patient Verification', () => {
    it('should verify patient exists', async () => {
      const patient = await prisma.patient.findUnique({
        where: { id: mockPatientId },
      });

      expect(patient).toBeDefined();
      expect(patient.id).toBe(mockPatientId);
    });

    it('should return error when patient not found', async () => {
      (prisma.patient.findUnique as AnyMock).mockResolvedValue(null);

      const patient = await prisma.patient.findUnique({
        where: { id: 'non-existent' },
      });

      expect(patient).toBeNull();
    });
  });

  describe('Referral Creation', () => {
    it('should create referral as ProviderTask with required fields', async () => {
      const referralData = {
        title: 'Referral to Cardiology',
        description: 'Reason: High cardiovascular risk - ASCVD 12.5%\nPatient: Jane Doe',
        category: 'FOLLOW_UP',
        priority: 'NORMAL',
        status: 'PENDING',
        assignedTo: mockUserId,
        relatedType: 'Patient',
        relatedId: mockPatientId,
        autoGenerated: true,
        generatedBy: 'prevention_hub_referral',
      };

      const created = await prisma.providerTask.create({
        data: referralData,
      });

      expect(prisma.providerTask.create).toHaveBeenCalledWith({
        data: referralData,
      });
      expect(created.id).toBe(mockReferralId);
      expect(created.status).toBe('PENDING');
    });

    it('should create referral with urgent priority', async () => {
      const urgentTask = {
        ...mockReferralTask,
        priority: 'URGENT',
      };
      (prisma.providerTask.create as AnyMock).mockResolvedValue(urgentTask);

      const created = await prisma.providerTask.create({
        data: {
          title: 'Referral to Oncology',
          description: 'Reason: Suspicious mass found\nPatient: Jane Doe',
          category: 'FOLLOW_UP',
          priority: 'URGENT',
          status: 'PENDING',
          assignedTo: mockUserId,
          relatedType: 'Patient',
          relatedId: mockPatientId,
          autoGenerated: true,
          generatedBy: 'prevention_hub_referral',
        },
      });

      expect(created.priority).toBe('URGENT');
    });

    it('should link referral to intervention via screening update', async () => {
      await prisma.screeningOutcome.update({
        where: { id: mockInterventionId },
        data: {
          notes: 'Referral to Cardiology placed. Reason: High cardiovascular risk',
        },
      });

      expect(prisma.screeningOutcome.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: mockInterventionId },
          data: expect.objectContaining({
            notes: expect.stringContaining('Referral'),
          }),
        })
      );
    });
  });

  describe('HIPAA Audit Logging', () => {
    it('should log referral creation', async () => {
      await auditCreate('Referral', mockReferralId, {}, {
        action: 'referral_created',
        specialty: 'Cardiology',
        patientId: mockPatientId,
        createdBy: mockUserId,
      });

      expect(auditCreate).toHaveBeenCalledWith(
        'Referral',
        mockReferralId,
        expect.anything(),
        expect.objectContaining({
          action: 'referral_created',
        })
      );
    });
  });

  describe('Error Handling', () => {
    it('should handle database errors', async () => {
      (prisma.providerTask.create as AnyMock).mockRejectedValue(
        new Error('Database connection failed')
      );

      await expect(
        prisma.providerTask.create({ data: {} })
      ).rejects.toThrow('Database connection failed');
    });
  });

  describe('Response Format', () => {
    it('should return created referral data in expected format', async () => {
      const created = await prisma.providerTask.create({
        data: {
          title: 'Referral to Cardiology',
          description: 'Reason: High cardiovascular risk\nPatient: Jane Doe',
          category: 'FOLLOW_UP',
          priority: 'NORMAL',
          status: 'PENDING',
          assignedTo: mockUserId,
          relatedType: 'Patient',
          relatedId: mockPatientId,
          autoGenerated: true,
          generatedBy: 'prevention_hub_referral',
        },
      });

      const response = {
        success: true,
        data: {
          referral: {
            id: created.id,
            patientId: mockPatientId,
            specialty: 'Cardiology',
            referralType: 'consultation',
            reason: 'High cardiovascular risk',
            urgency: 'routine',
            status: 'PENDING',
            createdAt: created.createdAt,
          },
        },
        meta: {
          latencyMs: 10,
        },
      };

      expect(response.success).toBe(true);
      expect(response.data.referral.id).toBeDefined();
      expect(response.data.referral.status).toBe('PENDING');
      expect(response.meta.latencyMs).toBeDefined();
    });
  });
});
