# ============================================================================
# DigitalOcean App Platform Specification
# Holi Labs - Healthcare Platform
# ============================================================================

name: holi-labs
region: nyc

services:
  - name: web
    source_dir: /
    dockerfile_path: Dockerfile
    
    health_check:
      http_path: /
      initial_delay_seconds: 30
    
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    
    instance_count: 1
    instance_size_slug: professional-xs
    http_port: 3000
    
    routes:
      - path: /

databases:
  - name: holi-labs-db
    engine: PG
    version: "15"
    production: true
